= Thesis Manuscript

Thesis manuscript written in AsciiDoc with conversion configs/scripts.

== Dependencies/Setup

An install script is provided for convenience:

[source,powershell]
----
./install
----

[NOTE]
====
After installing, before trying to do your first build, you must first update MiKTeX by doing the following:

* Open the MiKTeX Console (start menu search)
* Click `+Check for updates+`
* Once done, go to the `+Updates+` tab and click `+Update now+`
====

This will install the following:

* Scoop
** pandoc
** pdftk
** miktex
** msys2
** ruby
* Ruby
** asciidoctor
** asciidoctor-bibtex

== Building

A build script is provided for convenience:

[source,powershell]
----
./build
----

[NOTE]
====
Running this for the first time will prompt you to install LaTeX packages.

* *Install all of them* (you can uncheck the `+always show this dialogue+` option)
* This will take a few minutes, since you have to download and install all the needed packages. *Do not interrupt this*
====

The build pipeline goes like this:

----
asciidoc -> [asciidoctor] -> docbook -> [pandoc] -> latex -> [xelatex] -> pdf
----
